"""Add conflict field to record

Revision ID: 93d80f2a34b1
Revises: b381d1b7c584
Create Date: 2025-02-16 12:31:38.470572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d80f2a34b1'
down_revision = 'b381d1b7c584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conflict', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('record', schema=None) as batch_op:
        batch_op.drop_column('conflict')

    # ### end Alembic commands ###
