"""empty message

Revision ID: dec8815e7178
Revises: 8eed2c7359a1
Create Date: 2025-02-16 18:09:32.730169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dec8815e7178'
down_revision = '8eed2c7359a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('position')
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
